#pragma once
#define SOLAR_OS_PACKAGE_SERVICE_I2C 1
#define SOLAR_OS_PACKAGE_SERVICE_SPI 0
#define SOLAR_OS_PACKAGE_SERVICE_UART 0
#define SOLAR_OS_PACKAGE_SERVICE_ONEWIRE 0
#define SOLAR_OS_PACKAGE_SERVICE_PS2 0
