#pragma once
#ifndef SOLAR_OS_PACKAGE_SERVICE_VISION
#define SOLAR_OS_PACKAGE_SERVICE_VISION 1
#endif
#ifndef SOLAR_OS_PACKAGE_SERVICE_INFERENCE
#define SOLAR_OS_PACKAGE_SERVICE_INFERENCE 1
#endif
#define SOLAR_OS_PACKAGE_SERVICE_RTSP_CLIENT 1
