// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ESPDL_ESPDL_H_
#define FLATBUFFERS_GENERATED_ESPDL_ESPDL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace espdl {

struct AttributeF;

struct AttributeI;

struct Attribute;
struct AttributeBuilder;

struct ValueInfo;
struct ValueInfoBuilder;

struct Node;
struct NodeBuilder;

struct Model;
struct ModelBuilder;

struct StringStringEntry;
struct StringStringEntryBuilder;

struct TensorAnnotation;
struct TensorAnnotationBuilder;

struct Graph;
struct GraphBuilder;

struct AlignedBytes;

struct Tensor;
struct TensorBuilder;

struct TensorShape;
struct TensorShapeBuilder;

struct Dimension;
struct DimensionBuilder;

struct DimensionValue;
struct DimensionValueBuilder;

struct TensorTypeAndShape;
struct TensorTypeAndShapeBuilder;

struct SequenceType;
struct SequenceTypeBuilder;

struct MapType;
struct MapTypeBuilder;

struct OptionalType;
struct OptionalTypeBuilder;

struct TypeInfo;
struct TypeInfoBuilder;

struct OperatorSetId;
struct OperatorSetIdBuilder;

struct Function;
struct FunctionBuilder;

enum Version : int32_t {
  Version__START_VERSION = 0,
  Version_IR_VERSION_2023_12_22 = 1,
  Version_MIN = Version__START_VERSION,
  Version_MAX = Version_IR_VERSION_2023_12_22
};

inline const Version (&EnumValuesVersion())[2] {
  static const Version values[] = {
    Version__START_VERSION,
    Version_IR_VERSION_2023_12_22
  };
  return values;
}

inline const char * const *EnumNamesVersion() {
  static const char * const names[3] = {
    "_START_VERSION",
    "IR_VERSION_2023_12_22",
    nullptr
  };
  return names;
}

inline const char *EnumNameVersion(Version e) {
  if (flatbuffers::IsOutRange(e, Version__START_VERSION, Version_IR_VERSION_2023_12_22)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesVersion()[index];
}

enum AttributeType : int32_t {
  AttributeType_UNDEFINED = 0,
  AttributeType_FLOAT = 1,
  AttributeType_INT = 2,
  AttributeType_STRING = 3,
  AttributeType_TENSOR = 4,
  AttributeType_GRAPH = 5,
  AttributeType_FLOATS = 6,
  AttributeType_INTS = 7,
  AttributeType_STRINGS = 8,
  AttributeType_TENSORS = 9,
  AttributeType_GRAPHS = 10,
  AttributeType_TYPE_FBS = 11,
  AttributeType_TYPE_FBSS = 12,
  AttributeType_MIN = AttributeType_UNDEFINED,
  AttributeType_MAX = AttributeType_TYPE_FBSS
};

inline const AttributeType (&EnumValuesAttributeType())[13] {
  static const AttributeType values[] = {
    AttributeType_UNDEFINED,
    AttributeType_FLOAT,
    AttributeType_INT,
    AttributeType_STRING,
    AttributeType_TENSOR,
    AttributeType_GRAPH,
    AttributeType_FLOATS,
    AttributeType_INTS,
    AttributeType_STRINGS,
    AttributeType_TENSORS,
    AttributeType_GRAPHS,
    AttributeType_TYPE_FBS,
    AttributeType_TYPE_FBSS
  };
  return values;
}

inline const char * const *EnumNamesAttributeType() {
  static const char * const names[14] = {
    "UNDEFINED",
    "FLOAT",
    "INT",
    "STRING",
    "TENSOR",
    "GRAPH",
    "FLOATS",
    "INTS",
    "STRINGS",
    "TENSORS",
    "GRAPHS",
    "TYPE_FBS",
    "TYPE_FBSS",
    nullptr
  };
  return names;
}

inline const char *EnumNameAttributeType(AttributeType e) {
  if (flatbuffers::IsOutRange(e, AttributeType_UNDEFINED, AttributeType_TYPE_FBSS)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAttributeType()[index];
}

enum TensorDataType : int32_t {
  TensorDataType_UNDEFINED = 0,
  TensorDataType_FLOAT = 1,
  TensorDataType_UINT8 = 2,
  TensorDataType_INT8 = 3,
  TensorDataType_UINT16 = 4,
  TensorDataType_INT16 = 5,
  TensorDataType_INT32 = 6,
  TensorDataType_INT64 = 7,
  TensorDataType_STRING = 8,
  TensorDataType_BOOL = 9,
  TensorDataType_FLOAT16 = 10,
  TensorDataType_DOUBLE = 11,
  TensorDataType_UINT32 = 12,
  TensorDataType_UINT64 = 13,
  TensorDataType_MIN = TensorDataType_UNDEFINED,
  TensorDataType_MAX = TensorDataType_UINT64
};

inline const TensorDataType (&EnumValuesTensorDataType())[14] {
  static const TensorDataType values[] = {
    TensorDataType_UNDEFINED,
    TensorDataType_FLOAT,
    TensorDataType_UINT8,
    TensorDataType_INT8,
    TensorDataType_UINT16,
    TensorDataType_INT16,
    TensorDataType_INT32,
    TensorDataType_INT64,
    TensorDataType_STRING,
    TensorDataType_BOOL,
    TensorDataType_FLOAT16,
    TensorDataType_DOUBLE,
    TensorDataType_UINT32,
    TensorDataType_UINT64
  };
  return values;
}

inline const char * const *EnumNamesTensorDataType() {
  static const char * const names[15] = {
    "UNDEFINED",
    "FLOAT",
    "UINT8",
    "INT8",
    "UINT16",
    "INT16",
    "INT32",
    "INT64",
    "STRING",
    "BOOL",
    "FLOAT16",
    "DOUBLE",
    "UINT32",
    "UINT64",
    nullptr
  };
  return names;
}

inline const char *EnumNameTensorDataType(TensorDataType e) {
  if (flatbuffers::IsOutRange(e, TensorDataType_UNDEFINED, TensorDataType_UINT64)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTensorDataType()[index];
}

enum DataLocation : int32_t {
  DataLocation_DEFAULT = 0,
  DataLocation_EXTERNAL = 1,
  DataLocation_MIN = DataLocation_DEFAULT,
  DataLocation_MAX = DataLocation_EXTERNAL
};

inline const DataLocation (&EnumValuesDataLocation())[2] {
  static const DataLocation values[] = {
    DataLocation_DEFAULT,
    DataLocation_EXTERNAL
  };
  return values;
}

inline const char * const *EnumNamesDataLocation() {
  static const char * const names[3] = {
    "DEFAULT",
    "EXTERNAL",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataLocation(DataLocation e) {
  if (flatbuffers::IsOutRange(e, DataLocation_DEFAULT, DataLocation_EXTERNAL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataLocation()[index];
}

enum DimensionValueType : int8_t {
  DimensionValueType_UNKNOWN = 0,
  DimensionValueType_VALUE = 1,
  DimensionValueType_PARAM = 2,
  DimensionValueType_MIN = DimensionValueType_UNKNOWN,
  DimensionValueType_MAX = DimensionValueType_PARAM
};

inline const DimensionValueType (&EnumValuesDimensionValueType())[3] {
  static const DimensionValueType values[] = {
    DimensionValueType_UNKNOWN,
    DimensionValueType_VALUE,
    DimensionValueType_PARAM
  };
  return values;
}

inline const char * const *EnumNamesDimensionValueType() {
  static const char * const names[4] = {
    "UNKNOWN",
    "VALUE",
    "PARAM",
    nullptr
  };
  return names;
}

inline const char *EnumNameDimensionValueType(DimensionValueType e) {
  if (flatbuffers::IsOutRange(e, DimensionValueType_UNKNOWN, DimensionValueType_PARAM)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDimensionValueType()[index];
}

enum TypeInfoValue : uint8_t {
  TypeInfoValue_NONE = 0,
  TypeInfoValue_tensor_type = 1,
  TypeInfoValue_sequence_type = 2,
  TypeInfoValue_map_type = 3,
  TypeInfoValue_optional_type = 4,
  TypeInfoValue_MIN = TypeInfoValue_NONE,
  TypeInfoValue_MAX = TypeInfoValue_optional_type
};

inline const TypeInfoValue (&EnumValuesTypeInfoValue())[5] {
  static const TypeInfoValue values[] = {
    TypeInfoValue_NONE,
    TypeInfoValue_tensor_type,
    TypeInfoValue_sequence_type,
    TypeInfoValue_map_type,
    TypeInfoValue_optional_type
  };
  return values;
}

inline const char * const *EnumNamesTypeInfoValue() {
  static const char * const names[6] = {
    "NONE",
    "tensor_type",
    "sequence_type",
    "map_type",
    "optional_type",
    nullptr
  };
  return names;
}

inline const char *EnumNameTypeInfoValue(TypeInfoValue e) {
  if (flatbuffers::IsOutRange(e, TypeInfoValue_NONE, TypeInfoValue_optional_type)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTypeInfoValue()[index];
}

template<typename T> struct TypeInfoValueTraits {
  static const TypeInfoValue enum_value = TypeInfoValue_NONE;
};

template<> struct TypeInfoValueTraits<espdl::TensorTypeAndShape> {
  static const TypeInfoValue enum_value = TypeInfoValue_tensor_type;
};

template<> struct TypeInfoValueTraits<espdl::SequenceType> {
  static const TypeInfoValue enum_value = TypeInfoValue_sequence_type;
};

template<> struct TypeInfoValueTraits<espdl::MapType> {
  static const TypeInfoValue enum_value = TypeInfoValue_map_type;
};

template<> struct TypeInfoValueTraits<espdl::OptionalType> {
  static const TypeInfoValue enum_value = TypeInfoValue_optional_type;
};

bool VerifyTypeInfoValue(flatbuffers::Verifier &verifier, const void *obj, TypeInfoValue type);
bool VerifyTypeInfoValueVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) AttributeF FLATBUFFERS_FINAL_CLASS {
 private:
  float f_;

 public:
  AttributeF()
      : f_(0) {
  }
  AttributeF(float _f)
      : f_(flatbuffers::EndianScalar(_f)) {
  }
  float f() const {
    return flatbuffers::EndianScalar(f_);
  }
};
FLATBUFFERS_STRUCT_END(AttributeF, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) AttributeI FLATBUFFERS_FINAL_CLASS {
 private:
  int64_t i_;

 public:
  AttributeI()
      : i_(0) {
  }
  AttributeI(int64_t _i)
      : i_(flatbuffers::EndianScalar(_i)) {
  }
  int64_t i() const {
    return flatbuffers::EndianScalar(i_);
  }
};
FLATBUFFERS_STRUCT_END(AttributeI, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(16) AlignedBytes FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t bytes_[16];

 public:
  AlignedBytes()
      : bytes_() {
  }
  AlignedBytes(flatbuffers::span<const uint8_t, 16> _bytes) {
    flatbuffers::CastToArray(bytes_).CopyFromSpan(_bytes);
  }
  const flatbuffers::Array<uint8_t, 16> *bytes() const {
    return &flatbuffers::CastToArray(bytes_);
  }
};
FLATBUFFERS_STRUCT_END(AlignedBytes, 16);

struct Attribute FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AttributeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_REF_ATTR_NAME = 6,
    VT_DOC_STRING = 8,
    VT_ATTR_TYPE = 10,
    VT_F = 12,
    VT_I = 14,
    VT_S = 16,
    VT_T = 18,
    VT_G = 20,
    VT_TP = 22,
    VT_FLOATS = 24,
    VT_INTS = 26,
    VT_STRINGS = 28,
    VT_TENSORS = 30,
    VT_GRAPHS = 32,
    VT_TYPE_PROTOS = 34
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *ref_attr_name() const {
    return GetPointer<const flatbuffers::String *>(VT_REF_ATTR_NAME);
  }
  const flatbuffers::String *doc_string() const {
    return GetPointer<const flatbuffers::String *>(VT_DOC_STRING);
  }
  espdl::AttributeType attr_type() const {
    return static_cast<espdl::AttributeType>(GetField<int32_t>(VT_ATTR_TYPE, 0));
  }
  const espdl::AttributeF *f() const {
    return GetStruct<const espdl::AttributeF *>(VT_F);
  }
  const espdl::AttributeI *i() const {
    return GetStruct<const espdl::AttributeI *>(VT_I);
  }
  const flatbuffers::Vector<uint8_t> *s() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_S);
  }
  const espdl::Tensor *t() const {
    return GetPointer<const espdl::Tensor *>(VT_T);
  }
  const espdl::Graph *g() const {
    return GetPointer<const espdl::Graph *>(VT_G);
  }
  const espdl::TypeInfo *tp() const {
    return GetPointer<const espdl::TypeInfo *>(VT_TP);
  }
  const flatbuffers::Vector<float> *floats() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_FLOATS);
  }
  const flatbuffers::Vector<int64_t> *ints() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_INTS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *strings() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_STRINGS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>> *tensors() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>> *>(VT_TENSORS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Graph>> *graphs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Graph>> *>(VT_GRAPHS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::TypeInfo>> *type_protos() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::TypeInfo>> *>(VT_TYPE_PROTOS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_REF_ATTR_NAME) &&
           verifier.VerifyString(ref_attr_name()) &&
           VerifyOffset(verifier, VT_DOC_STRING) &&
           verifier.VerifyString(doc_string()) &&
           VerifyField<int32_t>(verifier, VT_ATTR_TYPE, 4) &&
           VerifyField<espdl::AttributeF>(verifier, VT_F, 4) &&
           VerifyField<espdl::AttributeI>(verifier, VT_I, 8) &&
           VerifyOffset(verifier, VT_S) &&
           verifier.VerifyVector(s()) &&
           VerifyOffset(verifier, VT_T) &&
           verifier.VerifyTable(t()) &&
           VerifyOffset(verifier, VT_G) &&
           verifier.VerifyTable(g()) &&
           VerifyOffset(verifier, VT_TP) &&
           verifier.VerifyTable(tp()) &&
           VerifyOffset(verifier, VT_FLOATS) &&
           verifier.VerifyVector(floats()) &&
           VerifyOffset(verifier, VT_INTS) &&
           verifier.VerifyVector(ints()) &&
           VerifyOffset(verifier, VT_STRINGS) &&
           verifier.VerifyVector(strings()) &&
           verifier.VerifyVectorOfStrings(strings()) &&
           VerifyOffset(verifier, VT_TENSORS) &&
           verifier.VerifyVector(tensors()) &&
           verifier.VerifyVectorOfTables(tensors()) &&
           VerifyOffset(verifier, VT_GRAPHS) &&
           verifier.VerifyVector(graphs()) &&
           verifier.VerifyVectorOfTables(graphs()) &&
           VerifyOffset(verifier, VT_TYPE_PROTOS) &&
           verifier.VerifyVector(type_protos()) &&
           verifier.VerifyVectorOfTables(type_protos()) &&
           verifier.EndTable();
  }
};

struct AttributeBuilder {
  typedef Attribute Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Attribute::VT_NAME, name);
  }
  void add_ref_attr_name(flatbuffers::Offset<flatbuffers::String> ref_attr_name) {
    fbb_.AddOffset(Attribute::VT_REF_ATTR_NAME, ref_attr_name);
  }
  void add_doc_string(flatbuffers::Offset<flatbuffers::String> doc_string) {
    fbb_.AddOffset(Attribute::VT_DOC_STRING, doc_string);
  }
  void add_attr_type(espdl::AttributeType attr_type) {
    fbb_.AddElement<int32_t>(Attribute::VT_ATTR_TYPE, static_cast<int32_t>(attr_type), 0);
  }
  void add_f(const espdl::AttributeF *f) {
    fbb_.AddStruct(Attribute::VT_F, f);
  }
  void add_i(const espdl::AttributeI *i) {
    fbb_.AddStruct(Attribute::VT_I, i);
  }
  void add_s(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> s) {
    fbb_.AddOffset(Attribute::VT_S, s);
  }
  void add_t(flatbuffers::Offset<espdl::Tensor> t) {
    fbb_.AddOffset(Attribute::VT_T, t);
  }
  void add_g(flatbuffers::Offset<espdl::Graph> g) {
    fbb_.AddOffset(Attribute::VT_G, g);
  }
  void add_tp(flatbuffers::Offset<espdl::TypeInfo> tp) {
    fbb_.AddOffset(Attribute::VT_TP, tp);
  }
  void add_floats(flatbuffers::Offset<flatbuffers::Vector<float>> floats) {
    fbb_.AddOffset(Attribute::VT_FLOATS, floats);
  }
  void add_ints(flatbuffers::Offset<flatbuffers::Vector<int64_t>> ints) {
    fbb_.AddOffset(Attribute::VT_INTS, ints);
  }
  void add_strings(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> strings) {
    fbb_.AddOffset(Attribute::VT_STRINGS, strings);
  }
  void add_tensors(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>>> tensors) {
    fbb_.AddOffset(Attribute::VT_TENSORS, tensors);
  }
  void add_graphs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Graph>>> graphs) {
    fbb_.AddOffset(Attribute::VT_GRAPHS, graphs);
  }
  void add_type_protos(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::TypeInfo>>> type_protos) {
    fbb_.AddOffset(Attribute::VT_TYPE_PROTOS, type_protos);
  }
  explicit AttributeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Attribute> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Attribute>(end);
    return o;
  }
};

inline flatbuffers::Offset<Attribute> CreateAttribute(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> ref_attr_name = 0,
    flatbuffers::Offset<flatbuffers::String> doc_string = 0,
    espdl::AttributeType attr_type = espdl::AttributeType_UNDEFINED,
    const espdl::AttributeF *f = nullptr,
    const espdl::AttributeI *i = nullptr,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> s = 0,
    flatbuffers::Offset<espdl::Tensor> t = 0,
    flatbuffers::Offset<espdl::Graph> g = 0,
    flatbuffers::Offset<espdl::TypeInfo> tp = 0,
    flatbuffers::Offset<flatbuffers::Vector<float>> floats = 0,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> ints = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> strings = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>>> tensors = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Graph>>> graphs = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::TypeInfo>>> type_protos = 0) {
  AttributeBuilder builder_(_fbb);
  builder_.add_type_protos(type_protos);
  builder_.add_graphs(graphs);
  builder_.add_tensors(tensors);
  builder_.add_strings(strings);
  builder_.add_ints(ints);
  builder_.add_floats(floats);
  builder_.add_tp(tp);
  builder_.add_g(g);
  builder_.add_t(t);
  builder_.add_s(s);
  builder_.add_i(i);
  builder_.add_f(f);
  builder_.add_attr_type(attr_type);
  builder_.add_doc_string(doc_string);
  builder_.add_ref_attr_name(ref_attr_name);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Attribute> CreateAttributeDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *ref_attr_name = nullptr,
    const char *doc_string = nullptr,
    espdl::AttributeType attr_type = espdl::AttributeType_UNDEFINED,
    const espdl::AttributeF *f = nullptr,
    const espdl::AttributeI *i = nullptr,
    const std::vector<uint8_t> *s = nullptr,
    flatbuffers::Offset<espdl::Tensor> t = 0,
    flatbuffers::Offset<espdl::Graph> g = 0,
    flatbuffers::Offset<espdl::TypeInfo> tp = 0,
    const std::vector<float> *floats = nullptr,
    const std::vector<int64_t> *ints = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *strings = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Tensor>> *tensors = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Graph>> *graphs = nullptr,
    const std::vector<flatbuffers::Offset<espdl::TypeInfo>> *type_protos = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto ref_attr_name__ = ref_attr_name ? _fbb.CreateString(ref_attr_name) : 0;
  auto doc_string__ = doc_string ? _fbb.CreateString(doc_string) : 0;
  auto s__ = s ? _fbb.CreateVector<uint8_t>(*s) : 0;
  auto floats__ = floats ? _fbb.CreateVector<float>(*floats) : 0;
  auto ints__ = ints ? _fbb.CreateVector<int64_t>(*ints) : 0;
  auto strings__ = strings ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*strings) : 0;
  auto tensors__ = tensors ? _fbb.CreateVector<flatbuffers::Offset<espdl::Tensor>>(*tensors) : 0;
  auto graphs__ = graphs ? _fbb.CreateVector<flatbuffers::Offset<espdl::Graph>>(*graphs) : 0;
  auto type_protos__ = type_protos ? _fbb.CreateVector<flatbuffers::Offset<espdl::TypeInfo>>(*type_protos) : 0;
  return espdl::CreateAttribute(
      _fbb,
      name__,
      ref_attr_name__,
      doc_string__,
      attr_type,
      f,
      i,
      s__,
      t,
      g,
      tp,
      floats__,
      ints__,
      strings__,
      tensors__,
      graphs__,
      type_protos__);
}

struct ValueInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ValueInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE_INFO_TYPE = 6,
    VT_DOC_STRING = 8,
    VT_EXPONENTS = 10
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const espdl::TypeInfo *value_info_type() const {
    return GetPointer<const espdl::TypeInfo *>(VT_VALUE_INFO_TYPE);
  }
  const flatbuffers::String *doc_string() const {
    return GetPointer<const flatbuffers::String *>(VT_DOC_STRING);
  }
  const flatbuffers::Vector<int64_t> *exponents() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_EXPONENTS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_VALUE_INFO_TYPE) &&
           verifier.VerifyTable(value_info_type()) &&
           VerifyOffset(verifier, VT_DOC_STRING) &&
           verifier.VerifyString(doc_string()) &&
           VerifyOffset(verifier, VT_EXPONENTS) &&
           verifier.VerifyVector(exponents()) &&
           verifier.EndTable();
  }
};

struct ValueInfoBuilder {
  typedef ValueInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(ValueInfo::VT_NAME, name);
  }
  void add_value_info_type(flatbuffers::Offset<espdl::TypeInfo> value_info_type) {
    fbb_.AddOffset(ValueInfo::VT_VALUE_INFO_TYPE, value_info_type);
  }
  void add_doc_string(flatbuffers::Offset<flatbuffers::String> doc_string) {
    fbb_.AddOffset(ValueInfo::VT_DOC_STRING, doc_string);
  }
  void add_exponents(flatbuffers::Offset<flatbuffers::Vector<int64_t>> exponents) {
    fbb_.AddOffset(ValueInfo::VT_EXPONENTS, exponents);
  }
  explicit ValueInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ValueInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ValueInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<ValueInfo> CreateValueInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<espdl::TypeInfo> value_info_type = 0,
    flatbuffers::Offset<flatbuffers::String> doc_string = 0,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> exponents = 0) {
  ValueInfoBuilder builder_(_fbb);
  builder_.add_exponents(exponents);
  builder_.add_doc_string(doc_string);
  builder_.add_value_info_type(value_info_type);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<ValueInfo> CreateValueInfoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    flatbuffers::Offset<espdl::TypeInfo> value_info_type = 0,
    const char *doc_string = nullptr,
    const std::vector<int64_t> *exponents = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto doc_string__ = doc_string ? _fbb.CreateString(doc_string) : 0;
  auto exponents__ = exponents ? _fbb.CreateVector<int64_t>(*exponents) : 0;
  return espdl::CreateValueInfo(
      _fbb,
      name__,
      value_info_type,
      doc_string__,
      exponents__);
}

struct Node FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef NodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INPUT = 4,
    VT_OUTPUT = 6,
    VT_NAME = 8,
    VT_OP_TYPE = 10,
    VT_DOMAIN = 12,
    VT_ATTRIBUTE = 14,
    VT_DOC_STRING = 16
  };
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *input() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_INPUT);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *output() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_OUTPUT);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *op_type() const {
    return GetPointer<const flatbuffers::String *>(VT_OP_TYPE);
  }
  const flatbuffers::String *domain() const {
    return GetPointer<const flatbuffers::String *>(VT_DOMAIN);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Attribute>> *attribute() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Attribute>> *>(VT_ATTRIBUTE);
  }
  const flatbuffers::String *doc_string() const {
    return GetPointer<const flatbuffers::String *>(VT_DOC_STRING);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INPUT) &&
           verifier.VerifyVector(input()) &&
           verifier.VerifyVectorOfStrings(input()) &&
           VerifyOffset(verifier, VT_OUTPUT) &&
           verifier.VerifyVector(output()) &&
           verifier.VerifyVectorOfStrings(output()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_OP_TYPE) &&
           verifier.VerifyString(op_type()) &&
           VerifyOffset(verifier, VT_DOMAIN) &&
           verifier.VerifyString(domain()) &&
           VerifyOffset(verifier, VT_ATTRIBUTE) &&
           verifier.VerifyVector(attribute()) &&
           verifier.VerifyVectorOfTables(attribute()) &&
           VerifyOffset(verifier, VT_DOC_STRING) &&
           verifier.VerifyString(doc_string()) &&
           verifier.EndTable();
  }
};

struct NodeBuilder {
  typedef Node Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_input(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> input) {
    fbb_.AddOffset(Node::VT_INPUT, input);
  }
  void add_output(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> output) {
    fbb_.AddOffset(Node::VT_OUTPUT, output);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Node::VT_NAME, name);
  }
  void add_op_type(flatbuffers::Offset<flatbuffers::String> op_type) {
    fbb_.AddOffset(Node::VT_OP_TYPE, op_type);
  }
  void add_domain(flatbuffers::Offset<flatbuffers::String> domain) {
    fbb_.AddOffset(Node::VT_DOMAIN, domain);
  }
  void add_attribute(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Attribute>>> attribute) {
    fbb_.AddOffset(Node::VT_ATTRIBUTE, attribute);
  }
  void add_doc_string(flatbuffers::Offset<flatbuffers::String> doc_string) {
    fbb_.AddOffset(Node::VT_DOC_STRING, doc_string);
  }
  explicit NodeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Node> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Node>(end);
    return o;
  }
};

inline flatbuffers::Offset<Node> CreateNode(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> input = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> output = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> op_type = 0,
    flatbuffers::Offset<flatbuffers::String> domain = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Attribute>>> attribute = 0,
    flatbuffers::Offset<flatbuffers::String> doc_string = 0) {
  NodeBuilder builder_(_fbb);
  builder_.add_doc_string(doc_string);
  builder_.add_attribute(attribute);
  builder_.add_domain(domain);
  builder_.add_op_type(op_type);
  builder_.add_name(name);
  builder_.add_output(output);
  builder_.add_input(input);
  return builder_.Finish();
}

inline flatbuffers::Offset<Node> CreateNodeDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *input = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *output = nullptr,
    const char *name = nullptr,
    const char *op_type = nullptr,
    const char *domain = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Attribute>> *attribute = nullptr,
    const char *doc_string = nullptr) {
  auto input__ = input ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*input) : 0;
  auto output__ = output ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*output) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto op_type__ = op_type ? _fbb.CreateString(op_type) : 0;
  auto domain__ = domain ? _fbb.CreateString(domain) : 0;
  auto attribute__ = attribute ? _fbb.CreateVector<flatbuffers::Offset<espdl::Attribute>>(*attribute) : 0;
  auto doc_string__ = doc_string ? _fbb.CreateString(doc_string) : 0;
  return espdl::CreateNode(
      _fbb,
      input__,
      output__,
      name__,
      op_type__,
      domain__,
      attribute__,
      doc_string__);
}

struct Model FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ModelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IR_VERSION = 4,
    VT_OPSET_IMPORT = 6,
    VT_PRODUCER_NAME = 8,
    VT_PRODUCER_VERSION = 10,
    VT_DOMAIN = 12,
    VT_MODEL_VERSION = 14,
    VT_DOC_STRING = 16,
    VT_GRAPH = 18,
    VT_METADATA_PROPS = 20,
    VT_FUNCTIONS = 22
  };
  int32_t ir_version() const {
    return GetField<int32_t>(VT_IR_VERSION, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::OperatorSetId>> *opset_import() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::OperatorSetId>> *>(VT_OPSET_IMPORT);
  }
  const flatbuffers::String *producer_name() const {
    return GetPointer<const flatbuffers::String *>(VT_PRODUCER_NAME);
  }
  const flatbuffers::String *producer_version() const {
    return GetPointer<const flatbuffers::String *>(VT_PRODUCER_VERSION);
  }
  const flatbuffers::String *domain() const {
    return GetPointer<const flatbuffers::String *>(VT_DOMAIN);
  }
  int64_t model_version() const {
    return GetField<int64_t>(VT_MODEL_VERSION, 0);
  }
  const flatbuffers::String *doc_string() const {
    return GetPointer<const flatbuffers::String *>(VT_DOC_STRING);
  }
  const espdl::Graph *graph() const {
    return GetPointer<const espdl::Graph *>(VT_GRAPH);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>> *metadata_props() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>> *>(VT_METADATA_PROPS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Function>> *functions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Function>> *>(VT_FUNCTIONS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_IR_VERSION, 4) &&
           VerifyOffset(verifier, VT_OPSET_IMPORT) &&
           verifier.VerifyVector(opset_import()) &&
           verifier.VerifyVectorOfTables(opset_import()) &&
           VerifyOffset(verifier, VT_PRODUCER_NAME) &&
           verifier.VerifyString(producer_name()) &&
           VerifyOffset(verifier, VT_PRODUCER_VERSION) &&
           verifier.VerifyString(producer_version()) &&
           VerifyOffset(verifier, VT_DOMAIN) &&
           verifier.VerifyString(domain()) &&
           VerifyField<int64_t>(verifier, VT_MODEL_VERSION, 8) &&
           VerifyOffset(verifier, VT_DOC_STRING) &&
           verifier.VerifyString(doc_string()) &&
           VerifyOffset(verifier, VT_GRAPH) &&
           verifier.VerifyTable(graph()) &&
           VerifyOffset(verifier, VT_METADATA_PROPS) &&
           verifier.VerifyVector(metadata_props()) &&
           verifier.VerifyVectorOfTables(metadata_props()) &&
           VerifyOffset(verifier, VT_FUNCTIONS) &&
           verifier.VerifyVector(functions()) &&
           verifier.VerifyVectorOfTables(functions()) &&
           verifier.EndTable();
  }
};

struct ModelBuilder {
  typedef Model Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ir_version(int32_t ir_version) {
    fbb_.AddElement<int32_t>(Model::VT_IR_VERSION, ir_version, 0);
  }
  void add_opset_import(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::OperatorSetId>>> opset_import) {
    fbb_.AddOffset(Model::VT_OPSET_IMPORT, opset_import);
  }
  void add_producer_name(flatbuffers::Offset<flatbuffers::String> producer_name) {
    fbb_.AddOffset(Model::VT_PRODUCER_NAME, producer_name);
  }
  void add_producer_version(flatbuffers::Offset<flatbuffers::String> producer_version) {
    fbb_.AddOffset(Model::VT_PRODUCER_VERSION, producer_version);
  }
  void add_domain(flatbuffers::Offset<flatbuffers::String> domain) {
    fbb_.AddOffset(Model::VT_DOMAIN, domain);
  }
  void add_model_version(int64_t model_version) {
    fbb_.AddElement<int64_t>(Model::VT_MODEL_VERSION, model_version, 0);
  }
  void add_doc_string(flatbuffers::Offset<flatbuffers::String> doc_string) {
    fbb_.AddOffset(Model::VT_DOC_STRING, doc_string);
  }
  void add_graph(flatbuffers::Offset<espdl::Graph> graph) {
    fbb_.AddOffset(Model::VT_GRAPH, graph);
  }
  void add_metadata_props(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>>> metadata_props) {
    fbb_.AddOffset(Model::VT_METADATA_PROPS, metadata_props);
  }
  void add_functions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Function>>> functions) {
    fbb_.AddOffset(Model::VT_FUNCTIONS, functions);
  }
  explicit ModelBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Model> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Model>(end);
    return o;
  }
};

inline flatbuffers::Offset<Model> CreateModel(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t ir_version = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::OperatorSetId>>> opset_import = 0,
    flatbuffers::Offset<flatbuffers::String> producer_name = 0,
    flatbuffers::Offset<flatbuffers::String> producer_version = 0,
    flatbuffers::Offset<flatbuffers::String> domain = 0,
    int64_t model_version = 0,
    flatbuffers::Offset<flatbuffers::String> doc_string = 0,
    flatbuffers::Offset<espdl::Graph> graph = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>>> metadata_props = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Function>>> functions = 0) {
  ModelBuilder builder_(_fbb);
  builder_.add_model_version(model_version);
  builder_.add_functions(functions);
  builder_.add_metadata_props(metadata_props);
  builder_.add_graph(graph);
  builder_.add_doc_string(doc_string);
  builder_.add_domain(domain);
  builder_.add_producer_version(producer_version);
  builder_.add_producer_name(producer_name);
  builder_.add_opset_import(opset_import);
  builder_.add_ir_version(ir_version);
  return builder_.Finish();
}

inline flatbuffers::Offset<Model> CreateModelDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t ir_version = 0,
    const std::vector<flatbuffers::Offset<espdl::OperatorSetId>> *opset_import = nullptr,
    const char *producer_name = nullptr,
    const char *producer_version = nullptr,
    const char *domain = nullptr,
    int64_t model_version = 0,
    const char *doc_string = nullptr,
    flatbuffers::Offset<espdl::Graph> graph = 0,
    const std::vector<flatbuffers::Offset<espdl::StringStringEntry>> *metadata_props = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Function>> *functions = nullptr) {
  auto opset_import__ = opset_import ? _fbb.CreateVector<flatbuffers::Offset<espdl::OperatorSetId>>(*opset_import) : 0;
  auto producer_name__ = producer_name ? _fbb.CreateString(producer_name) : 0;
  auto producer_version__ = producer_version ? _fbb.CreateString(producer_version) : 0;
  auto domain__ = domain ? _fbb.CreateString(domain) : 0;
  auto doc_string__ = doc_string ? _fbb.CreateString(doc_string) : 0;
  auto metadata_props__ = metadata_props ? _fbb.CreateVector<flatbuffers::Offset<espdl::StringStringEntry>>(*metadata_props) : 0;
  auto functions__ = functions ? _fbb.CreateVector<flatbuffers::Offset<espdl::Function>>(*functions) : 0;
  return espdl::CreateModel(
      _fbb,
      ir_version,
      opset_import__,
      producer_name__,
      producer_version__,
      domain__,
      model_version,
      doc_string__,
      graph,
      metadata_props__,
      functions__);
}

struct StringStringEntry FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StringStringEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const flatbuffers::String *key() const {
    return GetPointer<const flatbuffers::String *>(VT_KEY);
  }
  const flatbuffers::String *value() const {
    return GetPointer<const flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct StringStringEntryBuilder {
  typedef StringStringEntry Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_key(flatbuffers::Offset<flatbuffers::String> key) {
    fbb_.AddOffset(StringStringEntry::VT_KEY, key);
  }
  void add_value(flatbuffers::Offset<flatbuffers::String> value) {
    fbb_.AddOffset(StringStringEntry::VT_VALUE, value);
  }
  explicit StringStringEntryBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<StringStringEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<StringStringEntry>(end);
    return o;
  }
};

inline flatbuffers::Offset<StringStringEntry> CreateStringStringEntry(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> key = 0,
    flatbuffers::Offset<flatbuffers::String> value = 0) {
  StringStringEntryBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline flatbuffers::Offset<StringStringEntry> CreateStringStringEntryDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const char *value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return espdl::CreateStringStringEntry(
      _fbb,
      key__,
      value__);
}

struct TensorAnnotation FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TensorAnnotationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TENSOR_NAME = 4,
    VT_QUANT_PARAMETER_TENSOR_NAMES = 6
  };
  const flatbuffers::String *tensor_name() const {
    return GetPointer<const flatbuffers::String *>(VT_TENSOR_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>> *quant_parameter_tensor_names() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>> *>(VT_QUANT_PARAMETER_TENSOR_NAMES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TENSOR_NAME) &&
           verifier.VerifyString(tensor_name()) &&
           VerifyOffset(verifier, VT_QUANT_PARAMETER_TENSOR_NAMES) &&
           verifier.VerifyVector(quant_parameter_tensor_names()) &&
           verifier.VerifyVectorOfTables(quant_parameter_tensor_names()) &&
           verifier.EndTable();
  }
};

struct TensorAnnotationBuilder {
  typedef TensorAnnotation Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_tensor_name(flatbuffers::Offset<flatbuffers::String> tensor_name) {
    fbb_.AddOffset(TensorAnnotation::VT_TENSOR_NAME, tensor_name);
  }
  void add_quant_parameter_tensor_names(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>>> quant_parameter_tensor_names) {
    fbb_.AddOffset(TensorAnnotation::VT_QUANT_PARAMETER_TENSOR_NAMES, quant_parameter_tensor_names);
  }
  explicit TensorAnnotationBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TensorAnnotation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TensorAnnotation>(end);
    return o;
  }
};

inline flatbuffers::Offset<TensorAnnotation> CreateTensorAnnotation(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> tensor_name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>>> quant_parameter_tensor_names = 0) {
  TensorAnnotationBuilder builder_(_fbb);
  builder_.add_quant_parameter_tensor_names(quant_parameter_tensor_names);
  builder_.add_tensor_name(tensor_name);
  return builder_.Finish();
}

inline flatbuffers::Offset<TensorAnnotation> CreateTensorAnnotationDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *tensor_name = nullptr,
    const std::vector<flatbuffers::Offset<espdl::StringStringEntry>> *quant_parameter_tensor_names = nullptr) {
  auto tensor_name__ = tensor_name ? _fbb.CreateString(tensor_name) : 0;
  auto quant_parameter_tensor_names__ = quant_parameter_tensor_names ? _fbb.CreateVector<flatbuffers::Offset<espdl::StringStringEntry>>(*quant_parameter_tensor_names) : 0;
  return espdl::CreateTensorAnnotation(
      _fbb,
      tensor_name__,
      quant_parameter_tensor_names__);
}

struct Graph FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GraphBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODE = 4,
    VT_NAME = 6,
    VT_INITIALIZER = 8,
    VT_DOC_STRING = 10,
    VT_INPUT = 12,
    VT_OUTPUT = 14,
    VT_VALUE_INFO = 16,
    VT_QUANTIZATION_ANNOTATION = 18,
    VT_TEST_INPUTS_VALUE = 20,
    VT_TEST_OUTPUTS_VALUE = 22
  };
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Node>> *node() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Node>> *>(VT_NODE);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>> *initializer() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>> *>(VT_INITIALIZER);
  }
  const flatbuffers::String *doc_string() const {
    return GetPointer<const flatbuffers::String *>(VT_DOC_STRING);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>> *input() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>> *>(VT_INPUT);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>> *output() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>> *>(VT_OUTPUT);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>> *value_info() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>> *>(VT_VALUE_INFO);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::TensorAnnotation>> *quantization_annotation() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::TensorAnnotation>> *>(VT_QUANTIZATION_ANNOTATION);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>> *test_inputs_value() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>> *>(VT_TEST_INPUTS_VALUE);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>> *test_outputs_value() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>> *>(VT_TEST_OUTPUTS_VALUE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODE) &&
           verifier.VerifyVector(node()) &&
           verifier.VerifyVectorOfTables(node()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_INITIALIZER) &&
           verifier.VerifyVector(initializer()) &&
           verifier.VerifyVectorOfTables(initializer()) &&
           VerifyOffset(verifier, VT_DOC_STRING) &&
           verifier.VerifyString(doc_string()) &&
           VerifyOffset(verifier, VT_INPUT) &&
           verifier.VerifyVector(input()) &&
           verifier.VerifyVectorOfTables(input()) &&
           VerifyOffset(verifier, VT_OUTPUT) &&
           verifier.VerifyVector(output()) &&
           verifier.VerifyVectorOfTables(output()) &&
           VerifyOffset(verifier, VT_VALUE_INFO) &&
           verifier.VerifyVector(value_info()) &&
           verifier.VerifyVectorOfTables(value_info()) &&
           VerifyOffset(verifier, VT_QUANTIZATION_ANNOTATION) &&
           verifier.VerifyVector(quantization_annotation()) &&
           verifier.VerifyVectorOfTables(quantization_annotation()) &&
           VerifyOffset(verifier, VT_TEST_INPUTS_VALUE) &&
           verifier.VerifyVector(test_inputs_value()) &&
           verifier.VerifyVectorOfTables(test_inputs_value()) &&
           VerifyOffset(verifier, VT_TEST_OUTPUTS_VALUE) &&
           verifier.VerifyVector(test_outputs_value()) &&
           verifier.VerifyVectorOfTables(test_outputs_value()) &&
           verifier.EndTable();
  }
};

struct GraphBuilder {
  typedef Graph Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_node(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Node>>> node) {
    fbb_.AddOffset(Graph::VT_NODE, node);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Graph::VT_NAME, name);
  }
  void add_initializer(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>>> initializer) {
    fbb_.AddOffset(Graph::VT_INITIALIZER, initializer);
  }
  void add_doc_string(flatbuffers::Offset<flatbuffers::String> doc_string) {
    fbb_.AddOffset(Graph::VT_DOC_STRING, doc_string);
  }
  void add_input(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>>> input) {
    fbb_.AddOffset(Graph::VT_INPUT, input);
  }
  void add_output(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>>> output) {
    fbb_.AddOffset(Graph::VT_OUTPUT, output);
  }
  void add_value_info(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>>> value_info) {
    fbb_.AddOffset(Graph::VT_VALUE_INFO, value_info);
  }
  void add_quantization_annotation(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::TensorAnnotation>>> quantization_annotation) {
    fbb_.AddOffset(Graph::VT_QUANTIZATION_ANNOTATION, quantization_annotation);
  }
  void add_test_inputs_value(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>>> test_inputs_value) {
    fbb_.AddOffset(Graph::VT_TEST_INPUTS_VALUE, test_inputs_value);
  }
  void add_test_outputs_value(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>>> test_outputs_value) {
    fbb_.AddOffset(Graph::VT_TEST_OUTPUTS_VALUE, test_outputs_value);
  }
  explicit GraphBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Graph> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Graph>(end);
    return o;
  }
};

inline flatbuffers::Offset<Graph> CreateGraph(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Node>>> node = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>>> initializer = 0,
    flatbuffers::Offset<flatbuffers::String> doc_string = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>>> input = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>>> output = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::ValueInfo>>> value_info = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::TensorAnnotation>>> quantization_annotation = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>>> test_inputs_value = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Tensor>>> test_outputs_value = 0) {
  GraphBuilder builder_(_fbb);
  builder_.add_test_outputs_value(test_outputs_value);
  builder_.add_test_inputs_value(test_inputs_value);
  builder_.add_quantization_annotation(quantization_annotation);
  builder_.add_value_info(value_info);
  builder_.add_output(output);
  builder_.add_input(input);
  builder_.add_doc_string(doc_string);
  builder_.add_initializer(initializer);
  builder_.add_name(name);
  builder_.add_node(node);
  return builder_.Finish();
}

inline flatbuffers::Offset<Graph> CreateGraphDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<espdl::Node>> *node = nullptr,
    const char *name = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Tensor>> *initializer = nullptr,
    const char *doc_string = nullptr,
    const std::vector<flatbuffers::Offset<espdl::ValueInfo>> *input = nullptr,
    const std::vector<flatbuffers::Offset<espdl::ValueInfo>> *output = nullptr,
    const std::vector<flatbuffers::Offset<espdl::ValueInfo>> *value_info = nullptr,
    const std::vector<flatbuffers::Offset<espdl::TensorAnnotation>> *quantization_annotation = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Tensor>> *test_inputs_value = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Tensor>> *test_outputs_value = nullptr) {
  auto node__ = node ? _fbb.CreateVector<flatbuffers::Offset<espdl::Node>>(*node) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto initializer__ = initializer ? _fbb.CreateVector<flatbuffers::Offset<espdl::Tensor>>(*initializer) : 0;
  auto doc_string__ = doc_string ? _fbb.CreateString(doc_string) : 0;
  auto input__ = input ? _fbb.CreateVector<flatbuffers::Offset<espdl::ValueInfo>>(*input) : 0;
  auto output__ = output ? _fbb.CreateVector<flatbuffers::Offset<espdl::ValueInfo>>(*output) : 0;
  auto value_info__ = value_info ? _fbb.CreateVector<flatbuffers::Offset<espdl::ValueInfo>>(*value_info) : 0;
  auto quantization_annotation__ = quantization_annotation ? _fbb.CreateVector<flatbuffers::Offset<espdl::TensorAnnotation>>(*quantization_annotation) : 0;
  auto test_inputs_value__ = test_inputs_value ? _fbb.CreateVector<flatbuffers::Offset<espdl::Tensor>>(*test_inputs_value) : 0;
  auto test_outputs_value__ = test_outputs_value ? _fbb.CreateVector<flatbuffers::Offset<espdl::Tensor>>(*test_outputs_value) : 0;
  return espdl::CreateGraph(
      _fbb,
      node__,
      name__,
      initializer__,
      doc_string__,
      input__,
      output__,
      value_info__,
      quantization_annotation__,
      test_inputs_value__,
      test_outputs_value__);
}

struct Tensor FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TensorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIMS = 4,
    VT_DATA_TYPE = 6,
    VT_FLOAT_DATA = 8,
    VT_INT32_DATA = 10,
    VT_STRING_DATA = 12,
    VT_INT64_DATA = 14,
    VT_NAME = 16,
    VT_DOC_STRING = 18,
    VT_RAW_DATA = 20,
    VT_EXTERNAL_DATA = 22,
    VT_DATA_LOCATION = 24,
    VT_DOUBLE_DATA = 26,
    VT_UINT64_DATA = 28,
    VT_EXPONENTS = 30
  };
  const flatbuffers::Vector<int64_t> *dims() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_DIMS);
  }
  espdl::TensorDataType data_type() const {
    return static_cast<espdl::TensorDataType>(GetField<int32_t>(VT_DATA_TYPE, 0));
  }
  const flatbuffers::Vector<float> *float_data() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_FLOAT_DATA);
  }
  const flatbuffers::Vector<int32_t> *int32_data() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_INT32_DATA);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *string_data() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_STRING_DATA);
  }
  const flatbuffers::Vector<int64_t> *int64_data() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_INT64_DATA);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *doc_string() const {
    return GetPointer<const flatbuffers::String *>(VT_DOC_STRING);
  }
  const flatbuffers::Vector<const espdl::AlignedBytes *> *raw_data() const {
    return GetPointer<const flatbuffers::Vector<const espdl::AlignedBytes *> *>(VT_RAW_DATA);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>> *external_data() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>> *>(VT_EXTERNAL_DATA);
  }
  espdl::DataLocation data_location() const {
    return static_cast<espdl::DataLocation>(GetField<int32_t>(VT_DATA_LOCATION, 0));
  }
  const flatbuffers::Vector<double> *double_data() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_DOUBLE_DATA);
  }
  const flatbuffers::Vector<uint64_t> *uint64_data() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_UINT64_DATA);
  }
  const flatbuffers::Vector<int64_t> *exponents() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_EXPONENTS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DIMS) &&
           verifier.VerifyVector(dims()) &&
           VerifyField<int32_t>(verifier, VT_DATA_TYPE, 4) &&
           VerifyOffset(verifier, VT_FLOAT_DATA) &&
           verifier.VerifyVector(float_data()) &&
           VerifyOffset(verifier, VT_INT32_DATA) &&
           verifier.VerifyVector(int32_data()) &&
           VerifyOffset(verifier, VT_STRING_DATA) &&
           verifier.VerifyVector(string_data()) &&
           verifier.VerifyVectorOfStrings(string_data()) &&
           VerifyOffset(verifier, VT_INT64_DATA) &&
           verifier.VerifyVector(int64_data()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_DOC_STRING) &&
           verifier.VerifyString(doc_string()) &&
           VerifyOffset(verifier, VT_RAW_DATA) &&
           verifier.VerifyVector(raw_data()) &&
           VerifyOffset(verifier, VT_EXTERNAL_DATA) &&
           verifier.VerifyVector(external_data()) &&
           verifier.VerifyVectorOfTables(external_data()) &&
           VerifyField<int32_t>(verifier, VT_DATA_LOCATION, 4) &&
           VerifyOffset(verifier, VT_DOUBLE_DATA) &&
           verifier.VerifyVector(double_data()) &&
           VerifyOffset(verifier, VT_UINT64_DATA) &&
           verifier.VerifyVector(uint64_data()) &&
           VerifyOffset(verifier, VT_EXPONENTS) &&
           verifier.VerifyVector(exponents()) &&
           verifier.EndTable();
  }
};

struct TensorBuilder {
  typedef Tensor Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_dims(flatbuffers::Offset<flatbuffers::Vector<int64_t>> dims) {
    fbb_.AddOffset(Tensor::VT_DIMS, dims);
  }
  void add_data_type(espdl::TensorDataType data_type) {
    fbb_.AddElement<int32_t>(Tensor::VT_DATA_TYPE, static_cast<int32_t>(data_type), 0);
  }
  void add_float_data(flatbuffers::Offset<flatbuffers::Vector<float>> float_data) {
    fbb_.AddOffset(Tensor::VT_FLOAT_DATA, float_data);
  }
  void add_int32_data(flatbuffers::Offset<flatbuffers::Vector<int32_t>> int32_data) {
    fbb_.AddOffset(Tensor::VT_INT32_DATA, int32_data);
  }
  void add_string_data(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> string_data) {
    fbb_.AddOffset(Tensor::VT_STRING_DATA, string_data);
  }
  void add_int64_data(flatbuffers::Offset<flatbuffers::Vector<int64_t>> int64_data) {
    fbb_.AddOffset(Tensor::VT_INT64_DATA, int64_data);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Tensor::VT_NAME, name);
  }
  void add_doc_string(flatbuffers::Offset<flatbuffers::String> doc_string) {
    fbb_.AddOffset(Tensor::VT_DOC_STRING, doc_string);
  }
  void add_raw_data(flatbuffers::Offset<flatbuffers::Vector<const espdl::AlignedBytes *>> raw_data) {
    fbb_.AddOffset(Tensor::VT_RAW_DATA, raw_data);
  }
  void add_external_data(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>>> external_data) {
    fbb_.AddOffset(Tensor::VT_EXTERNAL_DATA, external_data);
  }
  void add_data_location(espdl::DataLocation data_location) {
    fbb_.AddElement<int32_t>(Tensor::VT_DATA_LOCATION, static_cast<int32_t>(data_location), 0);
  }
  void add_double_data(flatbuffers::Offset<flatbuffers::Vector<double>> double_data) {
    fbb_.AddOffset(Tensor::VT_DOUBLE_DATA, double_data);
  }
  void add_uint64_data(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> uint64_data) {
    fbb_.AddOffset(Tensor::VT_UINT64_DATA, uint64_data);
  }
  void add_exponents(flatbuffers::Offset<flatbuffers::Vector<int64_t>> exponents) {
    fbb_.AddOffset(Tensor::VT_EXPONENTS, exponents);
  }
  explicit TensorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Tensor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Tensor>(end);
    return o;
  }
};

inline flatbuffers::Offset<Tensor> CreateTensor(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> dims = 0,
    espdl::TensorDataType data_type = espdl::TensorDataType_UNDEFINED,
    flatbuffers::Offset<flatbuffers::Vector<float>> float_data = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> int32_data = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> string_data = 0,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> int64_data = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> doc_string = 0,
    flatbuffers::Offset<flatbuffers::Vector<const espdl::AlignedBytes *>> raw_data = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::StringStringEntry>>> external_data = 0,
    espdl::DataLocation data_location = espdl::DataLocation_DEFAULT,
    flatbuffers::Offset<flatbuffers::Vector<double>> double_data = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> uint64_data = 0,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> exponents = 0) {
  TensorBuilder builder_(_fbb);
  builder_.add_exponents(exponents);
  builder_.add_uint64_data(uint64_data);
  builder_.add_double_data(double_data);
  builder_.add_data_location(data_location);
  builder_.add_external_data(external_data);
  builder_.add_raw_data(raw_data);
  builder_.add_doc_string(doc_string);
  builder_.add_name(name);
  builder_.add_int64_data(int64_data);
  builder_.add_string_data(string_data);
  builder_.add_int32_data(int32_data);
  builder_.add_float_data(float_data);
  builder_.add_data_type(data_type);
  builder_.add_dims(dims);
  return builder_.Finish();
}

inline flatbuffers::Offset<Tensor> CreateTensorDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int64_t> *dims = nullptr,
    espdl::TensorDataType data_type = espdl::TensorDataType_UNDEFINED,
    const std::vector<float> *float_data = nullptr,
    const std::vector<int32_t> *int32_data = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *string_data = nullptr,
    const std::vector<int64_t> *int64_data = nullptr,
    const char *name = nullptr,
    const char *doc_string = nullptr,
    const std::vector<espdl::AlignedBytes> *raw_data = nullptr,
    const std::vector<flatbuffers::Offset<espdl::StringStringEntry>> *external_data = nullptr,
    espdl::DataLocation data_location = espdl::DataLocation_DEFAULT,
    const std::vector<double> *double_data = nullptr,
    const std::vector<uint64_t> *uint64_data = nullptr,
    const std::vector<int64_t> *exponents = nullptr) {
  auto dims__ = dims ? _fbb.CreateVector<int64_t>(*dims) : 0;
  auto float_data__ = float_data ? _fbb.CreateVector<float>(*float_data) : 0;
  auto int32_data__ = int32_data ? _fbb.CreateVector<int32_t>(*int32_data) : 0;
  auto string_data__ = string_data ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*string_data) : 0;
  auto int64_data__ = int64_data ? _fbb.CreateVector<int64_t>(*int64_data) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto doc_string__ = doc_string ? _fbb.CreateString(doc_string) : 0;
  auto raw_data__ = raw_data ? _fbb.CreateVectorOfStructs<espdl::AlignedBytes>(*raw_data) : 0;
  auto external_data__ = external_data ? _fbb.CreateVector<flatbuffers::Offset<espdl::StringStringEntry>>(*external_data) : 0;
  auto double_data__ = double_data ? _fbb.CreateVector<double>(*double_data) : 0;
  auto uint64_data__ = uint64_data ? _fbb.CreateVector<uint64_t>(*uint64_data) : 0;
  auto exponents__ = exponents ? _fbb.CreateVector<int64_t>(*exponents) : 0;
  return espdl::CreateTensor(
      _fbb,
      dims__,
      data_type,
      float_data__,
      int32_data__,
      string_data__,
      int64_data__,
      name__,
      doc_string__,
      raw_data__,
      external_data__,
      data_location,
      double_data__,
      uint64_data__,
      exponents__);
}

struct TensorShape FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TensorShapeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIM = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Dimension>> *dim() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Dimension>> *>(VT_DIM);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DIM) &&
           verifier.VerifyVector(dim()) &&
           verifier.VerifyVectorOfTables(dim()) &&
           verifier.EndTable();
  }
};

struct TensorShapeBuilder {
  typedef TensorShape Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_dim(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Dimension>>> dim) {
    fbb_.AddOffset(TensorShape::VT_DIM, dim);
  }
  explicit TensorShapeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TensorShape> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TensorShape>(end);
    return o;
  }
};

inline flatbuffers::Offset<TensorShape> CreateTensorShape(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Dimension>>> dim = 0) {
  TensorShapeBuilder builder_(_fbb);
  builder_.add_dim(dim);
  return builder_.Finish();
}

inline flatbuffers::Offset<TensorShape> CreateTensorShapeDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<espdl::Dimension>> *dim = nullptr) {
  auto dim__ = dim ? _fbb.CreateVector<flatbuffers::Offset<espdl::Dimension>>(*dim) : 0;
  return espdl::CreateTensorShape(
      _fbb,
      dim__);
}

struct Dimension FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DimensionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4,
    VT_DENOTATION = 6
  };
  const espdl::DimensionValue *value() const {
    return GetPointer<const espdl::DimensionValue *>(VT_VALUE);
  }
  const flatbuffers::String *denotation() const {
    return GetPointer<const flatbuffers::String *>(VT_DENOTATION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           VerifyOffset(verifier, VT_DENOTATION) &&
           verifier.VerifyString(denotation()) &&
           verifier.EndTable();
  }
};

struct DimensionBuilder {
  typedef Dimension Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value(flatbuffers::Offset<espdl::DimensionValue> value) {
    fbb_.AddOffset(Dimension::VT_VALUE, value);
  }
  void add_denotation(flatbuffers::Offset<flatbuffers::String> denotation) {
    fbb_.AddOffset(Dimension::VT_DENOTATION, denotation);
  }
  explicit DimensionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Dimension> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Dimension>(end);
    return o;
  }
};

inline flatbuffers::Offset<Dimension> CreateDimension(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<espdl::DimensionValue> value = 0,
    flatbuffers::Offset<flatbuffers::String> denotation = 0) {
  DimensionBuilder builder_(_fbb);
  builder_.add_denotation(denotation);
  builder_.add_value(value);
  return builder_.Finish();
}

inline flatbuffers::Offset<Dimension> CreateDimensionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<espdl::DimensionValue> value = 0,
    const char *denotation = nullptr) {
  auto denotation__ = denotation ? _fbb.CreateString(denotation) : 0;
  return espdl::CreateDimension(
      _fbb,
      value,
      denotation__);
}

struct DimensionValue FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DimensionValueBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIM_TYPE = 4,
    VT_DIM_VALUE = 6,
    VT_DIM_PARAM = 8
  };
  espdl::DimensionValueType dim_type() const {
    return static_cast<espdl::DimensionValueType>(GetField<int8_t>(VT_DIM_TYPE, 0));
  }
  int64_t dim_value() const {
    return GetField<int64_t>(VT_DIM_VALUE, 0);
  }
  const flatbuffers::String *dim_param() const {
    return GetPointer<const flatbuffers::String *>(VT_DIM_PARAM);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_DIM_TYPE, 1) &&
           VerifyField<int64_t>(verifier, VT_DIM_VALUE, 8) &&
           VerifyOffset(verifier, VT_DIM_PARAM) &&
           verifier.VerifyString(dim_param()) &&
           verifier.EndTable();
  }
};

struct DimensionValueBuilder {
  typedef DimensionValue Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_dim_type(espdl::DimensionValueType dim_type) {
    fbb_.AddElement<int8_t>(DimensionValue::VT_DIM_TYPE, static_cast<int8_t>(dim_type), 0);
  }
  void add_dim_value(int64_t dim_value) {
    fbb_.AddElement<int64_t>(DimensionValue::VT_DIM_VALUE, dim_value, 0);
  }
  void add_dim_param(flatbuffers::Offset<flatbuffers::String> dim_param) {
    fbb_.AddOffset(DimensionValue::VT_DIM_PARAM, dim_param);
  }
  explicit DimensionValueBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<DimensionValue> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<DimensionValue>(end);
    return o;
  }
};

inline flatbuffers::Offset<DimensionValue> CreateDimensionValue(
    flatbuffers::FlatBufferBuilder &_fbb,
    espdl::DimensionValueType dim_type = espdl::DimensionValueType_UNKNOWN,
    int64_t dim_value = 0,
    flatbuffers::Offset<flatbuffers::String> dim_param = 0) {
  DimensionValueBuilder builder_(_fbb);
  builder_.add_dim_value(dim_value);
  builder_.add_dim_param(dim_param);
  builder_.add_dim_type(dim_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<DimensionValue> CreateDimensionValueDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    espdl::DimensionValueType dim_type = espdl::DimensionValueType_UNKNOWN,
    int64_t dim_value = 0,
    const char *dim_param = nullptr) {
  auto dim_param__ = dim_param ? _fbb.CreateString(dim_param) : 0;
  return espdl::CreateDimensionValue(
      _fbb,
      dim_type,
      dim_value,
      dim_param__);
}

struct TensorTypeAndShape FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TensorTypeAndShapeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ELEM_TYPE = 4,
    VT_SHAPE = 6
  };
  espdl::TensorDataType elem_type() const {
    return static_cast<espdl::TensorDataType>(GetField<int32_t>(VT_ELEM_TYPE, 0));
  }
  const espdl::TensorShape *shape() const {
    return GetPointer<const espdl::TensorShape *>(VT_SHAPE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ELEM_TYPE, 4) &&
           VerifyOffset(verifier, VT_SHAPE) &&
           verifier.VerifyTable(shape()) &&
           verifier.EndTable();
  }
};

struct TensorTypeAndShapeBuilder {
  typedef TensorTypeAndShape Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_elem_type(espdl::TensorDataType elem_type) {
    fbb_.AddElement<int32_t>(TensorTypeAndShape::VT_ELEM_TYPE, static_cast<int32_t>(elem_type), 0);
  }
  void add_shape(flatbuffers::Offset<espdl::TensorShape> shape) {
    fbb_.AddOffset(TensorTypeAndShape::VT_SHAPE, shape);
  }
  explicit TensorTypeAndShapeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TensorTypeAndShape> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TensorTypeAndShape>(end);
    return o;
  }
};

inline flatbuffers::Offset<TensorTypeAndShape> CreateTensorTypeAndShape(
    flatbuffers::FlatBufferBuilder &_fbb,
    espdl::TensorDataType elem_type = espdl::TensorDataType_UNDEFINED,
    flatbuffers::Offset<espdl::TensorShape> shape = 0) {
  TensorTypeAndShapeBuilder builder_(_fbb);
  builder_.add_shape(shape);
  builder_.add_elem_type(elem_type);
  return builder_.Finish();
}

struct SequenceType FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SequenceTypeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ELEM_TYPE = 4
  };
  const espdl::TypeInfo *elem_type() const {
    return GetPointer<const espdl::TypeInfo *>(VT_ELEM_TYPE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ELEM_TYPE) &&
           verifier.VerifyTable(elem_type()) &&
           verifier.EndTable();
  }
};

struct SequenceTypeBuilder {
  typedef SequenceType Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_elem_type(flatbuffers::Offset<espdl::TypeInfo> elem_type) {
    fbb_.AddOffset(SequenceType::VT_ELEM_TYPE, elem_type);
  }
  explicit SequenceTypeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SequenceType> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SequenceType>(end);
    return o;
  }
};

inline flatbuffers::Offset<SequenceType> CreateSequenceType(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<espdl::TypeInfo> elem_type = 0) {
  SequenceTypeBuilder builder_(_fbb);
  builder_.add_elem_type(elem_type);
  return builder_.Finish();
}

struct MapType FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MapTypeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY_TYPE = 4,
    VT_VALUE_TYPE = 6
  };
  espdl::TensorDataType key_type() const {
    return static_cast<espdl::TensorDataType>(GetField<int32_t>(VT_KEY_TYPE, 0));
  }
  const espdl::TypeInfo *value_type() const {
    return GetPointer<const espdl::TypeInfo *>(VT_VALUE_TYPE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_KEY_TYPE, 4) &&
           VerifyOffset(verifier, VT_VALUE_TYPE) &&
           verifier.VerifyTable(value_type()) &&
           verifier.EndTable();
  }
};

struct MapTypeBuilder {
  typedef MapType Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_key_type(espdl::TensorDataType key_type) {
    fbb_.AddElement<int32_t>(MapType::VT_KEY_TYPE, static_cast<int32_t>(key_type), 0);
  }
  void add_value_type(flatbuffers::Offset<espdl::TypeInfo> value_type) {
    fbb_.AddOffset(MapType::VT_VALUE_TYPE, value_type);
  }
  explicit MapTypeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MapType> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MapType>(end);
    return o;
  }
};

inline flatbuffers::Offset<MapType> CreateMapType(
    flatbuffers::FlatBufferBuilder &_fbb,
    espdl::TensorDataType key_type = espdl::TensorDataType_UNDEFINED,
    flatbuffers::Offset<espdl::TypeInfo> value_type = 0) {
  MapTypeBuilder builder_(_fbb);
  builder_.add_value_type(value_type);
  builder_.add_key_type(key_type);
  return builder_.Finish();
}

struct OptionalType FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef OptionalTypeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ELEM_TYPE = 4
  };
  const espdl::TypeInfo *elem_type() const {
    return GetPointer<const espdl::TypeInfo *>(VT_ELEM_TYPE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ELEM_TYPE) &&
           verifier.VerifyTable(elem_type()) &&
           verifier.EndTable();
  }
};

struct OptionalTypeBuilder {
  typedef OptionalType Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_elem_type(flatbuffers::Offset<espdl::TypeInfo> elem_type) {
    fbb_.AddOffset(OptionalType::VT_ELEM_TYPE, elem_type);
  }
  explicit OptionalTypeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<OptionalType> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<OptionalType>(end);
    return o;
  }
};

inline flatbuffers::Offset<OptionalType> CreateOptionalType(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<espdl::TypeInfo> elem_type = 0) {
  OptionalTypeBuilder builder_(_fbb);
  builder_.add_elem_type(elem_type);
  return builder_.Finish();
}

struct TypeInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TypeInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE_TYPE = 4,
    VT_VALUE = 6,
    VT_DENOTATION = 8
  };
  espdl::TypeInfoValue value_type() const {
    return static_cast<espdl::TypeInfoValue>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const espdl::TensorTypeAndShape *value_as_tensor_type() const {
    return value_type() == espdl::TypeInfoValue_tensor_type ? static_cast<const espdl::TensorTypeAndShape *>(value()) : nullptr;
  }
  const espdl::SequenceType *value_as_sequence_type() const {
    return value_type() == espdl::TypeInfoValue_sequence_type ? static_cast<const espdl::SequenceType *>(value()) : nullptr;
  }
  const espdl::MapType *value_as_map_type() const {
    return value_type() == espdl::TypeInfoValue_map_type ? static_cast<const espdl::MapType *>(value()) : nullptr;
  }
  const espdl::OptionalType *value_as_optional_type() const {
    return value_type() == espdl::TypeInfoValue_optional_type ? static_cast<const espdl::OptionalType *>(value()) : nullptr;
  }
  const flatbuffers::String *denotation() const {
    return GetPointer<const flatbuffers::String *>(VT_DENOTATION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifyTypeInfoValue(verifier, value(), value_type()) &&
           VerifyOffset(verifier, VT_DENOTATION) &&
           verifier.VerifyString(denotation()) &&
           verifier.EndTable();
  }
};

template<> inline const espdl::TensorTypeAndShape *TypeInfo::value_as<espdl::TensorTypeAndShape>() const {
  return value_as_tensor_type();
}

template<> inline const espdl::SequenceType *TypeInfo::value_as<espdl::SequenceType>() const {
  return value_as_sequence_type();
}

template<> inline const espdl::MapType *TypeInfo::value_as<espdl::MapType>() const {
  return value_as_map_type();
}

template<> inline const espdl::OptionalType *TypeInfo::value_as<espdl::OptionalType>() const {
  return value_as_optional_type();
}

struct TypeInfoBuilder {
  typedef TypeInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_value_type(espdl::TypeInfoValue value_type) {
    fbb_.AddElement<uint8_t>(TypeInfo::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(flatbuffers::Offset<void> value) {
    fbb_.AddOffset(TypeInfo::VT_VALUE, value);
  }
  void add_denotation(flatbuffers::Offset<flatbuffers::String> denotation) {
    fbb_.AddOffset(TypeInfo::VT_DENOTATION, denotation);
  }
  explicit TypeInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TypeInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TypeInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<TypeInfo> CreateTypeInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    espdl::TypeInfoValue value_type = espdl::TypeInfoValue_NONE,
    flatbuffers::Offset<void> value = 0,
    flatbuffers::Offset<flatbuffers::String> denotation = 0) {
  TypeInfoBuilder builder_(_fbb);
  builder_.add_denotation(denotation);
  builder_.add_value(value);
  builder_.add_value_type(value_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<TypeInfo> CreateTypeInfoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    espdl::TypeInfoValue value_type = espdl::TypeInfoValue_NONE,
    flatbuffers::Offset<void> value = 0,
    const char *denotation = nullptr) {
  auto denotation__ = denotation ? _fbb.CreateString(denotation) : 0;
  return espdl::CreateTypeInfo(
      _fbb,
      value_type,
      value,
      denotation__);
}

struct OperatorSetId FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef OperatorSetIdBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DOMAIN = 4,
    VT_VERSION = 6
  };
  const flatbuffers::String *domain() const {
    return GetPointer<const flatbuffers::String *>(VT_DOMAIN);
  }
  int64_t version() const {
    return GetField<int64_t>(VT_VERSION, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DOMAIN) &&
           verifier.VerifyString(domain()) &&
           VerifyField<int64_t>(verifier, VT_VERSION, 8) &&
           verifier.EndTable();
  }
};

struct OperatorSetIdBuilder {
  typedef OperatorSetId Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_domain(flatbuffers::Offset<flatbuffers::String> domain) {
    fbb_.AddOffset(OperatorSetId::VT_DOMAIN, domain);
  }
  void add_version(int64_t version) {
    fbb_.AddElement<int64_t>(OperatorSetId::VT_VERSION, version, 0);
  }
  explicit OperatorSetIdBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<OperatorSetId> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<OperatorSetId>(end);
    return o;
  }
};

inline flatbuffers::Offset<OperatorSetId> CreateOperatorSetId(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> domain = 0,
    int64_t version = 0) {
  OperatorSetIdBuilder builder_(_fbb);
  builder_.add_version(version);
  builder_.add_domain(domain);
  return builder_.Finish();
}

inline flatbuffers::Offset<OperatorSetId> CreateOperatorSetIdDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *domain = nullptr,
    int64_t version = 0) {
  auto domain__ = domain ? _fbb.CreateString(domain) : 0;
  return espdl::CreateOperatorSetId(
      _fbb,
      domain__,
      version);
}

struct Function FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FunctionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_INPUT = 6,
    VT_OUTPUT = 8,
    VT_ATTRIBUTE = 10,
    VT_ATTRIBUTE_PROTO = 12,
    VT_NODE = 14,
    VT_DOC_STRING = 16,
    VT_OPSET_IMPORT = 18,
    VT_DOMAIN = 20
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *input() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_INPUT);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *output() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_OUTPUT);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *attribute() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_ATTRIBUTE);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Attribute>> *attribute_proto() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Attribute>> *>(VT_ATTRIBUTE_PROTO);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::Node>> *node() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::Node>> *>(VT_NODE);
  }
  const flatbuffers::String *doc_string() const {
    return GetPointer<const flatbuffers::String *>(VT_DOC_STRING);
  }
  const flatbuffers::Vector<flatbuffers::Offset<espdl::OperatorSetId>> *opset_import() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<espdl::OperatorSetId>> *>(VT_OPSET_IMPORT);
  }
  const flatbuffers::String *domain() const {
    return GetPointer<const flatbuffers::String *>(VT_DOMAIN);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_INPUT) &&
           verifier.VerifyVector(input()) &&
           verifier.VerifyVectorOfStrings(input()) &&
           VerifyOffset(verifier, VT_OUTPUT) &&
           verifier.VerifyVector(output()) &&
           verifier.VerifyVectorOfStrings(output()) &&
           VerifyOffset(verifier, VT_ATTRIBUTE) &&
           verifier.VerifyVector(attribute()) &&
           verifier.VerifyVectorOfStrings(attribute()) &&
           VerifyOffset(verifier, VT_ATTRIBUTE_PROTO) &&
           verifier.VerifyVector(attribute_proto()) &&
           verifier.VerifyVectorOfTables(attribute_proto()) &&
           VerifyOffset(verifier, VT_NODE) &&
           verifier.VerifyVector(node()) &&
           verifier.VerifyVectorOfTables(node()) &&
           VerifyOffset(verifier, VT_DOC_STRING) &&
           verifier.VerifyString(doc_string()) &&
           VerifyOffset(verifier, VT_OPSET_IMPORT) &&
           verifier.VerifyVector(opset_import()) &&
           verifier.VerifyVectorOfTables(opset_import()) &&
           VerifyOffset(verifier, VT_DOMAIN) &&
           verifier.VerifyString(domain()) &&
           verifier.EndTable();
  }
};

struct FunctionBuilder {
  typedef Function Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Function::VT_NAME, name);
  }
  void add_input(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> input) {
    fbb_.AddOffset(Function::VT_INPUT, input);
  }
  void add_output(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> output) {
    fbb_.AddOffset(Function::VT_OUTPUT, output);
  }
  void add_attribute(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> attribute) {
    fbb_.AddOffset(Function::VT_ATTRIBUTE, attribute);
  }
  void add_attribute_proto(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Attribute>>> attribute_proto) {
    fbb_.AddOffset(Function::VT_ATTRIBUTE_PROTO, attribute_proto);
  }
  void add_node(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Node>>> node) {
    fbb_.AddOffset(Function::VT_NODE, node);
  }
  void add_doc_string(flatbuffers::Offset<flatbuffers::String> doc_string) {
    fbb_.AddOffset(Function::VT_DOC_STRING, doc_string);
  }
  void add_opset_import(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::OperatorSetId>>> opset_import) {
    fbb_.AddOffset(Function::VT_OPSET_IMPORT, opset_import);
  }
  void add_domain(flatbuffers::Offset<flatbuffers::String> domain) {
    fbb_.AddOffset(Function::VT_DOMAIN, domain);
  }
  explicit FunctionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Function> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Function>(end);
    return o;
  }
};

inline flatbuffers::Offset<Function> CreateFunction(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> input = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> output = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> attribute = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Attribute>>> attribute_proto = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::Node>>> node = 0,
    flatbuffers::Offset<flatbuffers::String> doc_string = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<espdl::OperatorSetId>>> opset_import = 0,
    flatbuffers::Offset<flatbuffers::String> domain = 0) {
  FunctionBuilder builder_(_fbb);
  builder_.add_domain(domain);
  builder_.add_opset_import(opset_import);
  builder_.add_doc_string(doc_string);
  builder_.add_node(node);
  builder_.add_attribute_proto(attribute_proto);
  builder_.add_attribute(attribute);
  builder_.add_output(output);
  builder_.add_input(input);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Function> CreateFunctionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *input = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *output = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *attribute = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Attribute>> *attribute_proto = nullptr,
    const std::vector<flatbuffers::Offset<espdl::Node>> *node = nullptr,
    const char *doc_string = nullptr,
    const std::vector<flatbuffers::Offset<espdl::OperatorSetId>> *opset_import = nullptr,
    const char *domain = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto input__ = input ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*input) : 0;
  auto output__ = output ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*output) : 0;
  auto attribute__ = attribute ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*attribute) : 0;
  auto attribute_proto__ = attribute_proto ? _fbb.CreateVector<flatbuffers::Offset<espdl::Attribute>>(*attribute_proto) : 0;
  auto node__ = node ? _fbb.CreateVector<flatbuffers::Offset<espdl::Node>>(*node) : 0;
  auto doc_string__ = doc_string ? _fbb.CreateString(doc_string) : 0;
  auto opset_import__ = opset_import ? _fbb.CreateVector<flatbuffers::Offset<espdl::OperatorSetId>>(*opset_import) : 0;
  auto domain__ = domain ? _fbb.CreateString(domain) : 0;
  return espdl::CreateFunction(
      _fbb,
      name__,
      input__,
      output__,
      attribute__,
      attribute_proto__,
      node__,
      doc_string__,
      opset_import__,
      domain__);
}

inline bool VerifyTypeInfoValue(flatbuffers::Verifier &verifier, const void *obj, TypeInfoValue type) {
  switch (type) {
    case TypeInfoValue_NONE: {
      return true;
    }
    case TypeInfoValue_tensor_type: {
      auto ptr = reinterpret_cast<const espdl::TensorTypeAndShape *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case TypeInfoValue_sequence_type: {
      auto ptr = reinterpret_cast<const espdl::SequenceType *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case TypeInfoValue_map_type: {
      auto ptr = reinterpret_cast<const espdl::MapType *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case TypeInfoValue_optional_type: {
      auto ptr = reinterpret_cast<const espdl::OptionalType *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyTypeInfoValueVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyTypeInfoValue(
        verifier,  values->Get(i), types->GetEnum<TypeInfoValue>(i))) {
      return false;
    }
  }
  return true;
}

inline const espdl::Model *GetModel(const void *buf) {
  return flatbuffers::GetRoot<espdl::Model>(buf);
}

inline const espdl::Model *GetSizePrefixedModel(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<espdl::Model>(buf);
}

inline bool VerifyModelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<espdl::Model>(nullptr);
}

inline bool VerifySizePrefixedModelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<espdl::Model>(nullptr);
}

inline void FinishModelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<espdl::Model> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedModelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<espdl::Model> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace espdl

#endif  // FLATBUFFERS_GENERATED_ESPDL_ESPDL_H_
