import importlib.util
from pathlib import Path
import sys
import tempfile
import unittest


REPOSITORY = Path(__file__).resolve().parents[1]
SCRIPTS = REPOSITORY / "scripts"
sys.path.insert(0, str(SCRIPTS))

GENERATOR_SPEC = importlib.util.spec_from_file_location(
    "generate_flavor_config", SCRIPTS / "generate_flavor_config.py"
)
generate_flavor_config = importlib.util.module_from_spec(GENERATOR_SPEC)
sys.modules[GENERATOR_SPEC.name] = generate_flavor_config
GENERATOR_SPEC.loader.exec_module(generate_flavor_config)

CONFIG_SPEC = importlib.util.spec_from_file_location(
    "flavor_config", SCRIPTS / "flavor_config.py"
)
flavor_config = importlib.util.module_from_spec(CONFIG_SPEC)
sys.modules[CONFIG_SPEC.name] = flavor_config
CONFIG_SPEC.loader.exec_module(flavor_config)


class FlavorConfigTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.catalog = generate_flavor_config.load_catalog(
            REPOSITORY / "packages" / "solar_os_packages.toml"
        )

    def test_tree_exposes_every_package(self):
        folders = flavor_config.folder_members(self.catalog)
        visible = {package for folder in folders for package in folder.members}
        self.assertEqual(visible, set(self.catalog.packages))
        by_name = {folder.name: folder for folder in folders}
        self.assertIn("service_expr", by_name["utils"].members)
        self.assertIn("service_script_runner", by_name["python"].members)
        self.assertIn("service_script_runner", by_name["lua"].members)
        self.assertEqual(by_name["experimental"].members, ("service_hid",))

    def test_folder_selectors_remain_direct_group_members(self):
        for folder in flavor_config.folder_members(self.catalog):
            self.assertEqual(
                folder.selectors,
                self.catalog.group_defs[folder.name].members,
            )

    def test_catalog_rejects_package_unreachable_from_every_group(self):
        content = (
            REPOSITORY / "packages" / "solar_os_packages.toml"
        ).read_text(encoding="utf-8")
        content += "\n[packages.test_orphan]\nlabel = \"test.orphan\"\n"
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "packages.toml"
            path.write_text(content, encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "not reachable from any group"):
                generate_flavor_config.load_catalog(path)

    def test_group_toggle_selects_all_children_and_allows_one_to_be_removed(self):
        model = flavor_config.SelectionModel(self.catalog)
        members = self.catalog.group_defs["games"].members
        model.toggle_group(members)
        self.assertTrue(set(members) <= model.selected)
        self.assertEqual(model.group_state(members), 2)

        model.toggle_package("app_gameboy")
        self.assertNotIn("app_gameboy", model.selected)
        self.assertIn("app_invaders", model.selected)
        self.assertEqual(model.group_state(members), 1)

    def test_disabling_transitive_dependency_also_disables_explicit_dependant(self):
        model = flavor_config.SelectionModel(self.catalog, {"app_curl"})
        self.assertIn("service_http_client", model.selected)
        self.assertIn("service_wifi", model.selected)
        model.toggle_package("service_wifi")
        self.assertNotIn("service_wifi", model.selected)
        self.assertNotIn("service_http_client", model.selected)
        self.assertNotIn("app_curl", model.selected)

    def test_bootstrap_dependency_is_locked(self):
        model = flavor_config.SelectionModel(self.catalog)
        self.assertIn("service_streams", model.mandatory)
        model.toggle_package("service_streams")
        self.assertIn("service_streams", model.selected)

    def test_rendered_flavor_round_trips_selected_packages(self):
        model = flavor_config.SelectionModel(
            self.catalog,
            set(self.catalog.group_defs["games"].members) | {"app_curl"},
        )
        content = flavor_config.render_flavor(
            "test-custom", "Generated by a test.", self.catalog, model
        )
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "test-custom.toml"
            path.write_text(content, encoding="utf-8")
            _, _, _, enabled = generate_flavor_config.load_flavor(path, self.catalog)
        resolved = {package for package, value in enabled.items() if value}
        self.assertEqual(resolved, model.selected)
        self.assertIn("games = true", content)

    def test_render_recognizes_complete_group_with_locked_member(self):
        requested = flavor_config.load_requested_packages(
            REPOSITORY / "flavors" / "core.toml", self.catalog
        )
        model = flavor_config.SelectionModel(self.catalog, requested)
        content = flavor_config.render_flavor("core-copy", "Test.", self.catalog, model)
        self.assertIn("system = true", content)
        self.assertNotIn("system_shell = true", content)

    def test_estimator_counts_shared_sources_and_requirements_once(self):
        estimator = flavor_config.FlashEstimator(
            self.catalog,
            {source: 10 for package in self.catalog.package_defs.values()
             for source in package.sources},
            {requirement: 100 for package in self.catalog.package_defs.values()
             for requirement in package.requires},
            "test",
        )
        packages = {"app_aplay", "app_arecord"}
        sources = {
            source
            for package in packages
            for source in self.catalog.package_defs[package].sources
        }
        requirements = {
            requirement
            for package in packages
            for requirement in self.catalog.package_defs[package].requires
        }
        expected = 10 * len(sources) + 100 * len(requirements)
        self.assertEqual(estimator.estimate(packages), expected)

    def test_top_bar_leads_with_total_image_size(self):
        text = flavor_config.top_bar_text(
            selected_count=163,
            package_count=163,
            image_size=5 * 1024 * 1024,
            bootstrap_size=2 * 1024 * 1024,
        )
        self.assertIn("image ~5.00 MiB", text)
        self.assertIn("+3.00 MiB optional", text)


if __name__ == "__main__":
    unittest.main()
