set(SOLAR_OS_BOARD_DISPLAY_DRIVER "vga32")

if(NOT DEFINED SOLAR_OS_VGA_MODE OR SOLAR_OS_VGA_MODE STREQUAL "")
    set(SOLAR_OS_VGA_MODE "320x200")
endif()
if(SOLAR_OS_VGA_MODE STREQUAL "320x200")
    list(APPEND SOLAR_OS_BOARD_COMPILE_DEFINITIONS
        SOLAR_OS_VGA_MODE_320X200=1
        SOLAR_OS_VGA_MODE_640X400=0
        SOLAR_OS_VGA_MODE_640X480=0
    )
elseif(SOLAR_OS_VGA_MODE STREQUAL "640x400")
    list(APPEND SOLAR_OS_BOARD_COMPILE_DEFINITIONS
        SOLAR_OS_VGA_MODE_320X200=0
        SOLAR_OS_VGA_MODE_640X400=1
        SOLAR_OS_VGA_MODE_640X480=0
    )
elseif(SOLAR_OS_VGA_MODE STREQUAL "640x480")
    list(APPEND SOLAR_OS_BOARD_COMPILE_DEFINITIONS
        SOLAR_OS_VGA_MODE_320X200=0
        SOLAR_OS_VGA_MODE_640X400=0
        SOLAR_OS_VGA_MODE_640X480=1
    )
else()
    message(FATAL_ERROR
        "Unsupported SOLAR_OS_VGA_MODE '${SOLAR_OS_VGA_MODE}'; "
        "expected 320x200, 640x400, or 640x480"
    )
endif()
message(STATUS "SolarOS VGA mode: ${SOLAR_OS_VGA_MODE}")

list(APPEND SOLAR_OS_BOARD_SRCS
    "board/solar_os_board_display_vga32.c"
    "drivers/vga32.c"
)
list(APPEND SOLAR_OS_BOARD_REQUIRES
    esp_driver_gpio
    esp_hw_support
    esp_rom
    esp_system
    hal
    u8g2
)
