# Defaults do not override values in an existing generated sdkconfig. Keep the
# exception runtime required by the selected defaults while retaining all other
# local configuration values. Run before ESP-IDF loads sdkconfig.
function(solar_os_enable_required_cxx_exceptions)
    if(DEFINED SDKCONFIG_DEFAULTS)
        set(defaults ${SDKCONFIG_DEFAULTS})
    else()
        set(defaults sdkconfig.defaults)
    endif()
    set(required FALSE)
    foreach(default IN LISTS defaults)
        get_filename_component(default "${default}" ABSOLUTE BASE_DIR "${CMAKE_SOURCE_DIR}")
        if(EXISTS "${default}")
            file(STRINGS "${default}" enabled REGEX "^CONFIG_COMPILER_CXX_EXCEPTIONS=y$")
            if(enabled)
                set(required TRUE)
            endif()
        endif()
    endforeach()
    if(NOT required)
        return()
    endif()
    if(SDKCONFIG)
        get_filename_component(config "${SDKCONFIG}" ABSOLUTE BASE_DIR "${CMAKE_SOURCE_DIR}")
    else()
        set(config "${CMAKE_SOURCE_DIR}/sdkconfig")
    endif()
    if(NOT EXISTS "${config}")
        return()
    endif()
    file(STRINGS "${config}" enabled REGEX "^CONFIG_COMPILER_CXX_EXCEPTIONS=y$")
    if(enabled)
        return()
    endif()
    get_filename_component(config_name "${config}" NAME)
    if(config_name MATCHES "^sdkconfig\\.defaults($|\\.)")
        message(FATAL_ERROR "SDKCONFIG must select a generated configuration, not defaults: ${config}")
    endif()
    file(READ "${config}" contents)
    string(REGEX REPLACE "(^|\n)(# CONFIG_COMPILER_CXX_EXCEPTIONS is not set|CONFIG_COMPILER_CXX_EXCEPTIONS=[^\n]*)" "\\1" contents "${contents}")
    file(WRITE "${config}" "${contents}\nCONFIG_COMPILER_CXX_EXCEPTIONS=y\n")
    message(NOTICE "SolarOS enabling required C++ exceptions in ${config}")
endfunction()
