#!/usr/bin/env python3
"""Compile shared profiles and optional overrides into firmware key tables."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

from solaros_keymap import PROFILE_DIR, PROFILE_IDS, load_profile, merge, read_json
from solaros_keymap_build import dependencies, resolve_selection

STEMS = {"tca8418": "tca8418", "inputronic-keyboard": "inputronic",
         "lilygo-pager-keyboard": "pager"}


def header(profile, layers) -> str:
    stem = STEMS[profile.id]
    count = max(profile.names) + 1
    lines = ["/* Generated by scripts/generate_keymaps.py. Do not edit. */",
             "#pragma once", '#include "solar_os_input_keymap_mapper.h"', "",
             f"#define SOLAR_OS_{stem.upper()}_KEYMAP_ROWS {profile.rows}U",
             f"#define SOLAR_OS_{stem.upper()}_KEYMAP_COLS {profile.cols}U", "",
             f"static const solar_os_input_keymap_key_t solar_os_{stem}_default_keys[2][{count}] = {{"]
    for entries in layers:
        lines.append("    {")
        for physical in sorted(entries):
            entry = entries[physical]
            if not entry:
                continue
            flags = 1 if entry.get("raw") else 2 if entry.get("layer_tap") else 4 if entry.get("alt_block") else 0
            lines.append(f"        [{physical}] = {{{entry.get('usage', 0)}, "
                         f"{entry.get('key', 0)}, {entry.get('shift_key', 0)}, {flags}}},")
        lines.append("    },")
    lines += ["};", ""]
    return "\n".join(lines)


def generate(directory: Path, *, root: Path, profile_dir=PROFILE_DIR,
             profile="", file="", index="") -> None:
    selected = resolve_selection(root, profile, file, index)
    # Validate all inputs before publishing any generated header.
    outputs = {}
    for name in PROFILE_IDS:
        definition = load_profile(name, profile_dir)
        layers = merge(definition, read_json(selected[name])) if name in selected else definition.layers
        outputs[directory / f"solar_os_{STEMS[name]}_keymap_generated.h"] = header(definition, layers)
    directory.mkdir(parents=True, exist_ok=True)
    for path, text in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--profile-dir", type=Path, default=PROFILE_DIR)
    parser.add_argument("--profile", default="")
    parser.add_argument("--file", default="")
    parser.add_argument("--index", default="")
    parser.add_argument("--dependencies", type=Path)
    args = parser.parse_args(argv)
    try:
        generate(args.output_dir, root=args.root, profile_dir=args.profile_dir,
                 profile=args.profile, file=args.file, index=args.index)
        if args.dependencies:
            paths = dependencies(args.root, args.profile, args.file, args.index)
            selected = resolve_selection(args.root, args.profile, args.file, args.index)
            packages = {"tca8418": "TCA8418", "inputronic-keyboard": "INPUTRONIC_KEYBOARD",
                        "lilygo-pager-keyboard": "LILYGO_PAGER_KEYBOARD"}
            def cmake_quote(value):
                marker = "="
                while f"]{marker}]" in value:
                    marker += "="
                return f"[{marker}[{value}]{marker}]"
            text = "set(SOLAR_OS_KEYMAP_INPUTS\n" + "".join(
                "    " + cmake_quote(path.as_posix()) + "\n" for path in paths) + ")\n"
            text += "set(SOLAR_OS_KEYMAP_REQUIRED_PACKAGES " + " ".join(
                packages[name] for name in selected) + ")\n"
            args.dependencies.write_text(text, encoding="utf-8")
    except (ValueError, OSError, UnicodeError) as exc:
        print(f"generate_keymaps: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
