#pragma once

#if defined(SOLAR_OS_BOARD_WAVESHARE_ESP32_S3_RLCD_4_2)
#include "boards/waveshare_esp32_s3_rlcd_4_2.h"
#elif defined(SOLAR_OS_BOARD_ESP32_S3_DEVKITC1_N16R8)
#include "boards/esp32_s3_devkitc1_n16r8.h"
#elif defined(SOLAR_OS_BOARD_ODROID_GO)
#include "boards/odroid_go.h"
#elif defined(SOLAR_OS_BOARD_FREENOVE_ESP32_WROVER_V3)
#include "boards/freenove_esp32_wrover_v3.h"
#elif defined(SOLAR_OS_BOARD_ELECROW_CROWPANEL_ESP32_S3_4_2_EPAPER)
#include "boards/elecrow_crowpanel_esp32_s3_4_2_epaper.h"
#elif defined(SOLAR_OS_BOARD_TTGO_VGA32_V14)
#include "boards/ttgo_vga32_v14.h"
#else
#error "No SolarOS board target selected. Build through a PlatformIO env with a matching boards/<target>.cmake profile."
#endif

#ifndef SOLAR_OS_BOARD_ID
#error "Selected SolarOS board header did not define SOLAR_OS_BOARD_ID."
#endif

#ifndef SOLAR_OS_BOARD_HAS_GPIO
#define SOLAR_OS_BOARD_HAS_GPIO 0
#endif

#ifndef SOLAR_OS_BOARD_GPIO_SLOTS
#if SOLAR_OS_BOARD_HAS_GPIO
#error "Selected SolarOS board header did not define SOLAR_OS_BOARD_GPIO_SLOTS."
#else
#define SOLAR_OS_BOARD_GPIO_SLOTS {{0}}
#endif
#endif

#ifndef SOLAR_OS_BOARD_USER_GPIO_MASK
#define SOLAR_OS_BOARD_USER_GPIO_MASK 0ULL
#endif

#ifndef SOLAR_OS_BOARD_EXPANSION_GPIO_MASK
#define SOLAR_OS_BOARD_EXPANSION_GPIO_MASK 0ULL
#endif

#ifndef SOLAR_OS_BOARD_BUSES
#define SOLAR_OS_BOARD_BUSES {{0}}
#endif

#ifndef SOLAR_OS_BOARD_AUTOSTART_PS2_BUS
#define SOLAR_OS_BOARD_AUTOSTART_PS2_BUS ""
#endif

#ifndef SOLAR_OS_BOARD_DEFAULT_BLE_ENABLED
#define SOLAR_OS_BOARD_DEFAULT_BLE_ENABLED 1
#endif

#ifndef SOLAR_OS_BOARD_DISPLAY_FRAME_INTERVAL_MS
#define SOLAR_OS_BOARD_DISPLAY_FRAME_INTERVAL_MS 0U
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_LAYOUT_TITLE
#define SOLAR_OS_BOARD_CONNECTOR_LAYOUT_TITLE "Expansion connectors"
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_LAYOUT_VIEW
#define SOLAR_OS_BOARD_CONNECTOR_LAYOUT_VIEW "component-side view"
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_LAYOUT_ROWS
#define SOLAR_OS_BOARD_CONNECTOR_LAYOUT_ROWS 0
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_LAYOUT_COLUMNS
#define SOLAR_OS_BOARD_CONNECTOR_LAYOUT_COLUMNS 0
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_PIN_COUNT
#define SOLAR_OS_BOARD_CONNECTOR_PIN_COUNT 0
#endif

#ifndef SOLAR_OS_BOARD_CONNECTOR_PINS
#define SOLAR_OS_BOARD_CONNECTOR_PINS {{0}}
#endif

#ifndef SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK
#define SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK 0U
#endif

#ifndef SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK
#define SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK 0U
#endif

#ifndef SOLAR_OS_BOARD_RUNTIME_I2S_PORT_MASK
#define SOLAR_OS_BOARD_RUNTIME_I2S_PORT_MASK 0U
#endif

#ifndef SOLAR_OS_BOARD_CPU_FLOOR_MHZ
#define SOLAR_OS_BOARD_CPU_FLOOR_MHZ 0U
#endif

#if SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK && !SOLAR_OS_BOARD_HAS_SPI
#error "SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK requires SOLAR_OS_BOARD_HAS_SPI"
#endif

#if SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK && !SOLAR_OS_BOARD_HAS_EXPANSION_SPI
#error "SOLAR_OS_BOARD_RUNTIME_SPI_HOST_MASK requires SOLAR_OS_BOARD_HAS_EXPANSION_SPI"
#endif

#if SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK && !SOLAR_OS_BOARD_HAS_UART
#error "SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK requires SOLAR_OS_BOARD_HAS_UART"
#endif

#if SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK && !SOLAR_OS_BOARD_HAS_EXPANSION_UART
#error "SOLAR_OS_BOARD_RUNTIME_UART_PORT_MASK requires SOLAR_OS_BOARD_HAS_EXPANSION_UART"
#endif

#if SOLAR_OS_BOARD_RUNTIME_I2S_PORT_MASK && !SOLAR_OS_BOARD_HAS_EXPANSION_I2S
#error "SOLAR_OS_BOARD_RUNTIME_I2S_PORT_MASK requires SOLAR_OS_BOARD_HAS_EXPANSION_I2S"
#endif

#ifndef SOLAR_OS_BOARD_EXPANSION_ADC_MASK
#define SOLAR_OS_BOARD_EXPANSION_ADC_MASK 0ULL
#endif

#ifndef SOLAR_OS_BOARD_EXPANSION_PWM_MASK
#define SOLAR_OS_BOARD_EXPANSION_PWM_MASK 0ULL
#endif
